-- MySQL Script generated by MySQL Workbench
-- Thu May 27 12:05:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema discursos_de_amlo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema discursos_de_amlo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `discursos_de_amlo` DEFAULT CHARACTER SET utf8 ;
USE `discursos_de_amlo` ;

-- -----------------------------------------------------
-- Table `discursos_de_amlo`.`Discurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `discursos_de_amlo`.`Discurso` (
  `id_discurso` INT NOT NULL,
  `Titulo` VARCHAR(1000) NULL,
  `Fecha` VARCHAR(1000) NULL,
  `URL` VARCHAR(1000) NULL,
  `Tipo` VARCHAR(1000) NULL,
  `Texto` TEXT(1000000) NULL,
  PRIMARY KEY (`id_discurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discursos_de_amlo`.`Multimedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `discursos_de_amlo`.`Multimedia` (
  `Discurso_id_discurso` INT NOT NULL,
  `url_imagen` VARCHAR(1000) NULL,
  `url_video` VARCHAR(1000) NULL,
  `url_audio` VARCHAR(1000) NULL,
  INDEX `fk_Multimedia_Discurso_idx` (`Discurso_id_discurso` ASC) VISIBLE,
  CONSTRAINT `fk_Multimedia_Discurso`
    FOREIGN KEY (`Discurso_id_discurso`)
    REFERENCES `discursos_de_amlo`.`Discurso` (`id_discurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
